name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type - major, minor or patch"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Package
        run: yarn build
        env:
          NODE_ENV: production
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
      - name: Create Changelog
        run: |
          git tag
          git log $(git describe --tags --abbrev=0)..HEAD --oneline &> ${{ github.workspace }}-CHANGELOG.txt
          cat ${{ github.workspace }}-CHANGELOG.txt
      - name: Setup Git
        run: |
          git config --global user.name "oss-stateful-bot"
          git config --global user.email "christian+wombot@stateful.com"
      - name: Package Extension
        run:  yarn vsce package ${{github.event.inputs.releaseType}} ${{github.event.inputs.additionalFlags}}
      - name: Release Extension
        run:  yarn vsce publish ${{github.event.inputs.releaseType}} -p ${{ secrets.VSCODE_PAT }} ${{github.event.inputs.additionalFlags}}
      - name: Push Tags
        run:  |
          LATEST_TAG=$(git describe --abbrev=0 | cut -c 2-)
          git tag $LATEST_TAG $LATEST_TAG^{} -f -m "v$LATEST_TAG"
          git push --tags
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./awesome-ux-*,foo/*.txt"
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
          tag: "$(git describe --abbrev=0 | cut -c 2-)"

