name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type - major, minor or patch"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Package
        run: yarn build
        env:
          NODE_ENV: production
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
      - name: Create Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --oneline &> ${{ github.workspace }}-CHANGELOG.txt
          cat ${{ github.workspace }}-CHANGELOG.txt
      - name: Setup Git
        run: |
          git config --global user.name "oss-stateful-bot"
          git config --global user.email "christian+wombot@stateful.com"
      - name: Package Extension
        run:  yarn vsce package ${{ github.event.inputs.releaseType }} --yarn --no-git-tag-version --no-update-package-json ${{ github.event.inputs.additionalFlags }}
      - name: Release Extension
        run:  yarn vsce publish ${{ github.event.inputs.releaseType }} --yarn -m "Release stateful.awesome-ux" -p ${{ secrets.VSCODE_PAT }} ${{ github.event.inputs.additionalFlags }}
      - name: Push Tags
        run: |
          git log -1 --stat
          git push origin main --tags
      - run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          echo "::set-env name=GIT_TAG::$GIT_TAG"
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./awesome-ux-*,foo/*.txt"
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
          tag: $GIT_TAG

