name: Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: |
            test/screenshots
            test/logs
