name: Tests
on: [push]

jobs:
  build:
    strategy:
      matrix:
        vscodeVersion:
          - stable
          - web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
        env:
          VSCODE_VERSION: ${{ matrix.vscodeVersion }}
          VSCODE_WEB_TESTS: ${{ matrix.vscodeVersion == 'web' && '1' || '0' }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: |
            test/screenshots
            test/logs
